### ISSUE TITLE
Solucionar problemes de compilació amb Maven

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1]
La llibreria seyconsession-common ja no existeix als repositoris de jboss i la generació de l'ear emprant Maven dona error.

S'ha d'afegir la llibreria al repositori local del projecte.

**Comment by josepg-limit** [comment]
Segueix donant error al compilar 

[ERROR] Failed to execute goal on project ripea-core: Could not resolve dependen
cies for project es.caib:ripea-core:ejb:0.1: Failed to collect dependencies for
[org.springframework.data:spring-data-jpa:jar:1.4.1.RELEASE (compile), joda-time
:joda-time:jar:1.6.2 (compile), net.sf.ehcache:ehcache:jar:1.6.1 (compile), org.
codehaus.groovy:groovy-all:jar:2.1.6 (compile), org.fusesource.jansi:jansi:jar:1
.11 (compile), jline:jline:jar:1.0 (compile), javax.mail:mail:jar:1.4.2 (provide
d), org.slf4j:slf4j-api:jar:1.5.8 (provided), javax.ejb:ejb-api:jar:3.0 (provide
d), javax.annotation:jsr250-api:jar:1.0 (provided), org.jboss.ws:jbossws-spi:jar
:1.1.2.GA (provided), jboss:jboss-annotations-ejb3:jar:4.2.2.GA (provided), es.c
aib.jboss:seyconsession-common:jar:1.5 (provided), jboss:jboss-jmx:jar:4.2.2.GA
(provided), junit:junit:jar:4.9 (test), org.springframework:spring-test:jar:3.2.
4.RELEASE (test), commons-logging:commons-logging:jar:1.1.3 (test), org.slf4j:sl
f4j-jcl:jar:1.5.8 (test), org.hsqldb:hsqldb:jar:2.3.2 (test), dumbster:dumbster:
jar:1.6 (test), es.caib:ripea-lib-common:pom:0.1 (compile)]: Failed to read arti
fact descriptor for es.caib.jboss:seyconsession-common:jar:1.5: Could not find a
rtifact es.caib.jboss:seyconsession:pom:1.5 in mvn-local-repo (file://E:\desenvo
lupament\projectes-interoperabilitat\ripea-1.0\ripea-core/../local-repo) -> [Hel
p 1]

**Comment by josepg-limit** [comment]
Ara dona un altre error:


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ripea-core: Compilation failure
[ERROR] \desenvolupament\projectes-interoperabilitat\ripea-1.0\ripea-core\src\main\java\es\caib\ripea\core\helper\WebServiceHelper.java:[49,15] cannot access es .caib.signatura.api.Signature
[ERROR] class file for es.caib.signatura.api.Signature not found
[ERROR] controlador.autenticar(userName, password);
[ERROR] -> [Help 1]

**Comment by smatas-dgtic** [comment]
Entenc que falten les classes de l'api de firma.

**Comment by josepg-limit** [comment]
Hola @smatas-dgtic, acabam d'afegir una nova dependència amb la llibreria caibsigner a veure si així es soluciona l'error de compilació.

El que ens estranya és que a noltros no ens dona aquest error.
