### ISSUE TITLE
Revisar casella obligat d'un interessat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1016]
No tenim molt clar pq serveix:

![image](https://user-images.githubusercontent.com/58417501/161229423-9694776b-d0fc-4472-abf0-00a6afadde12.png)

**Comment by josepg-limit** [comment]
Aquest és un camp definit a Notifica al especificar que es vol realitzar una entrega a DEH:

![image](https://user-images.githubusercontent.com/17267008/165233898-b0d9dedc-51d0-496d-8b8d-602edf0d83e6.png)

**Comment by acuevas-dgtic** [comment]
Doncs aquest camp només ha de sortir si la primera opció està activada
