### ISSUE TITLE
Revisar casella Incapacitat d'un interessat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1019]
Què fa exactament la casella "Incapacitat"? Té implicacions per alguna cosa, o és només informativa?

![image](https://user-images.githubusercontent.com/58417501/161230266-6ac1a73b-1d14-4709-862f-15ffbccf4835.png)

**Comment by josepg-limit** [comment]
Si es marca la casella incapacitat, s'està indicant que el titular no està capacitat per rebre notificacions.
En aquest cas, s'hauria d'informar un representant, que serà el que realment Notib posarà com a titular de la notificació.

**Comment by acuevas-dgtic** [comment]
Crec que aquest camp no apareix en Notib. SI no surt en Notib, tampoc en RIPEA
