### ISSUE TITLE
Millora de la interficie d'escaneig

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#1040]
S'ha de millorar la interficie per escanejar, hi ha algunes parts que se podrien obviar,
per exemple el botó d'aquesta pantalla,
![Captura de pantalla de 2022-04-25 09-33-52](https://user-images.githubusercontent.com/65942619/165050399-5bd9f5e6-2cd3-49c8-8851-f0aa115001a0.png)
ja que a la segona pantalla n'hi ha un altre per iniciar-ho
![Captura de pantalla de 2022-04-25 09-34-13](https://user-images.githubusercontent.com/65942619/165051169-5d0e09c8-f2a1-489f-9ae3-4b5a0c8b4c5a.png)
tot i que no se nota que sigui un botó
![Captura de pantalla de 2022-04-25 09-34-28](https://user-images.githubusercontent.com/65942619/165051353-aeda4119-20b7-4fc1-9267-fa1e306a7fa8.png)
a n'aquesta pantalla hi ha el relotge aquest, que esta fent voltes esperant a no se sap que...
![Captura de pantalla de 2022-04-25 09-41-22](https://user-images.githubusercontent.com/65942619/165051810-aeca3c3b-58ed-4a9e-bda8-ecf736720467.png)
si no tens el plugin instal·lat, la pantalla d'instalació del paquet, no hi cap dins la finestra, i l'acció queda amagada...

**Comment by acuevas-dgtic** [comment]
Si et deixes un camp obligatori del formulari de creació de document, torna a apareixer lel botó antic iniciar escaneig

![image](https://user-images.githubusercontent.com/58417501/190365133-d08c9f4f-cc02-4e16-ba43-d685c516574e.png)
