### ISSUE TITLE
Pantalles de seguiment d'enviaments per usuari

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1068]
Mostrar les pantalles d'enviament actuals de l'administrador d'entitat al perfil usuari. S'han de mostrar els enviaments fets a NOTIB i PORTAFIB dels expedients de l'usuari. A més afegir la següent informació a la taula:
- Concepte descripció
- Data finalització

**Comment by acuevas-dgtic** [comment]
No apareix el menú Consultar. El botó de dades estadístiques hauria d'estar també dins d'aquest menú. 

![Image](https://github.com/user-attachments/assets/c2747b2e-04a1-45ee-8abd-94115fe5e377)

![Image](https://github.com/user-attachments/assets/c17b4ded-93d8-4610-96d7-3d0c0ee9b38b)
