### ISSUE TITLE
Documents amb errors de validació de distribució

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1109]
Es realitzaran les modificacions oportunes per a admetre documents provinents de les anotacions de distribució amb errors de validació.

- [ ] Ús de API REST d'integració de Distribució
- [ ] Marcar els documents amb error de validació amb un símbol d'alerta i la informació de l'error

**Comment by acuevas-dgtic** [comment]
Han d'aparèixer com a esborranys
