### ISSUE TITLE
Arreglar problemes de dependències del plugin de validació de firmes

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1140]
Després d'una actualització del plugin de validació de firmes al repositori maven s'han produït errors de dependències amb plugins existents que s'han de resoldre. S'han de revisar les dependències afectades a Ripea i migrar-les per evitar l'error.

**Comment by acuevas-dgtic** [comment]
pareix que no carga correctament la propietat  es.caib.ripea.plugins.validatesignature.afirmacxf.authorization.ks.path que està definida en el fitxer .properties de Jboss

![image](https://user-images.githubusercontent.com/58417501/190376802-a295bc73-f625-4b45-b670-13f8281a0ae3.png)

**Comment by acuevas-dgtic** [comment]
Al subir un documento firmado tampoco detecta la firma

**Comment by acuevas-dgtic** [comment]
Faltaba por añadir varias propiedades de base de datos. Solucionado
