### ISSUE TITLE
No deixar tancar expedients amb documents pendent de firma

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1165]
Desactivar l'opció de tancar expedient si l'expedient conté documents pendents de firma (en protafirmes)

![imatge](https://user-images.githubusercontent.com/17267008/193802151-a687a127-bd0c-4874-a3b3-5ad15ada54ee.png)

**Comment by acuevas-dgtic** [comment]
Ha de sortir l'opció de firma en servidor com fins ara
