### ISSUE TITLE
crear nou document

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#1166]
Quan se crea un nou document amb firma se detecta bé el flag de "document amb firma" pero si el nom del document ja existeix, se torna a carregar sense el flag activat, i si s'activa, llavors ja nomes se pot marcar firma separada
![imagen](https://user-images.githubusercontent.com/65942619/194816287-d9c5ab67-ef1b-4fe9-b17b-829e0e8a5e79.png)

**Comment by acuevas-dgtic** [comment]
He comprobado que este error ya no se produce
