### ISSUE TITLE
No es mostren els estats d eles notificacions processades

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1209]
![image](https://user-images.githubusercontent.com/58417501/207034015-584c2785-1d98-45c6-972e-3cb576eff446.png)

**Comment by josepg-limit** [comment]
Ja resolt en la issue #1199 Error al consutar els detalls d'una remesa

**Comment by acuevas-dgtic** [comment]
En alguns casos només es mostra si el desplegues  (expedient testDGMAD/16/2022). 

![image](https://user-images.githubusercontent.com/58417501/218666571-bb6a05df-a818-4e19-b299-0a6bb541f87a.png)
