### ISSUE TITLE
A vegades surten notificacions sense enviaments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1254]
Per exemple tenim aquesta  notificació en estat "Processada" en RIPEA que no té cap enviament.

![image](https://user-images.githubusercontent.com/58417501/232440091-cbe4deee-f1ca-4f49-ad00-6d432625e277.png). 

En NOTIB surt com notificada amb totes les dades de l'enviament

**Comment by josepg-limit** [comment]
Actualmente no ocurre
