### ISSUE TITLE
La actualización del dir3 no ha actualizado la unidad de los expedientes abiertos 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1306]
Sí se han actualizado los procedimientos, pero no los expedientes. Al intentar hacer una notificación se obtiene un error de Notib como que la unidad está obsoleta.

![image](https://github.com/GovernIB/ripea/assets/58417501/151cd176-af70-4285-a1d2-00c25d5f27e8)
![image](https://github.com/GovernIB/ripea/assets/58417501/eb82dd8d-e2da-43ce-873e-c0a13af479e5)

**Comment by acuevas-dgtic** [comment]
Solucionado por script

**Comment by josepg-limit** [comment]
Se ha solucionado por script, pero és necesario modificar la aplicación para que no vuelva a suceder en las próximas actualizaciones
