### ISSUE TITLE
Afegir filtre per número d'assentament registral

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1332]
Poder filtrar els expedients en què es troba un assentament registral a partir del número de registre. Aquest filtre hauria de funcionar tant si s'importa un registre manualment (opció importar) com si arriba a través de la integració amb Distribució (Assentaments pendents).

**Comment by acuevas-dgtic** [comment]
No mostra cap resultat. Per exemple, per l'anotació GOIBE1030-DEV/2023 hauria d'aparèixer l'expedient CONS_EDU_PROC1/1/2023

**Comment by acuevas-dgtic** [comment]
Posar Número d'expedient en el camp corresponent

**Comment by acuevas-dgtic** [comment]
Tornar a afegir el literal "Firma pendent"
