### ISSUE TITLE
Permetre crear fluxos de firma a nivell d'usuari

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1369]
Crear un manteniment de fluxos de firma a nivell d’usuari. A més, permetre als usuaris guardar els fluxos que creen en el formulari d'enviament a Portafib. Aquests fluxos s'han de mostrar agrubats al desplegable 'Definir flux de firma'. 

![imagen](https://github.com/GovernIB/ripea/assets/17267008/7b0cff91-d215-4e0c-b109-9be3c24b44b1)

![imagen](https://github.com/GovernIB/ripea/assets/17267008/af1d6140-b920-475d-aec0-27eef57159a2)

**Comment by acuevas-dgtic** [comment]
Quina propietat hi ha que activar per poder gestionar els fluxos?

**Comment by josepg-limit** [comment]
La propiedad es es.caib.ripea.plugin.portafirmes.fluxos.usuaris

**Comment by acuevas-dgtic** [comment]
He activado la propiedad para probarla. He creado un flujo pero, una vez creado, no aparece en el listado

**Comment by josepg-limit** [comment]
Afegir nova columna amb els destinataris i reduir els botons de guardar

**Comment by acuevas-dgtic** [comment]
- [ ] La columna descripció no aporta res. Eliminar-la.

![image](https://github.com/GovernIB/ripea/assets/58417501/ac0f5b8d-90a2-4afb-a991-90929280d923)

- [ ] Veure si es pot afegir informació de firma obligatòria.
- [ ] En la selecció d'un flux de firma d'un document, canviar el text "Fluxos firma comuns" per "Fluxos de firma comuns" i "Fluxos firma usuari" per "Els meus fluxos".

![image](https://github.com/GovernIB/ripea/assets/58417501/fed8ade6-b1d2-419e-be44-a867d1161cca)

**Comment by acuevas-dgtic** [comment]
Modificar el títol de la secció "Gestió fluxos de firma" per "Gestió de fluxos de firma"

**Comment by acuevas-dgtic** [comment]
- [ ] No surten "els meus fluxos" en el desplegable si ets administrador d'entitat (si ets usuari si).
- [ ] "obligado" no està traduït. Ha de dir "obligatori".
- [ ] Ampliar la mida de la columna "Nom" i reduir la de la columna "Destinataris".
