### ISSUE TITLE
Crear regles per assignar anotacions a grups

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1417]
Actualment en procediments configurats amb grups. els usuaris només tenen accés als expedients que toca pel seu grup. Ara ens trobam amb que tots els usuaris d'un procediment i grups diferents tenen accés a totes les anotacions de registre del procediment, i això és un problema de protecció de dades. 

Per això cal crear un sistemes de regles on es pugui configurar quins grups poden veure les anotacions, donat el seu procediment i òrgan.

Depen de #584

**Comment by acuevas-dgtic** [comment]
No coincideix el número d'anotacions del menú amb el número d'anotacions del llistat

![image](https://github.com/GovernIB/ripea/assets/58417501/59b620b2-a812-4f69-abe3-5083553f99da)

**Comment by acuevas-dgtic** [comment]
He obert la issue #1460 per tractar el tema del número d'anotacions.
