### ISSUE TITLE
Permetre exportar els documents dels expedients seleccionats a un fitxer ZIP

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1421]
Afegir una nova acció massiva al llistat d'expedients per permetre descarregar tots els documents de varis expedients en format ZIP.

Remarques:
- Els documents han d'estar cadascun en una carpeta amb el número d'expedient dins del zip.
- Estudiar si és possible realitzar l'acció de forma asíncrona per temes de rendiment.
- Si el ZIP supera una mida màxima o se supera un temps de generació màxim definits per propietat s'ha de cancel·lar l'acció i mostrar un missatge a l'usuari per que provi a seleccionar menys expedients.

**Comment by acuevas-dgtic** [comment]
Habría que renombrar la acción existente de "Exportar fitxers ZIP" a "Exportar els documents dels expedients seleccionats".

**Comment by sandreu-limit** [comment]
Renombrada la opcion. A partir de aqui, esta tarea esta incluida dentro de la issue #1589 "Permetre descarregar massivament la versió imprimible dels documents d'un expedient".

Se comprobarán, cuando se instale la versión, los parametros de tiempo maximo de ejecución y tamaño máximo del fichero generado.

![Image](https://github.com/user-attachments/assets/16f0d648-1ea9-4e16-aae3-e3998e23bb77)
