### ISSUE TITLE
No es mostren el botó de crear document quan has seleccionat un fitxer

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1442]
![image](https://github.com/GovernIB/ripea/assets/58417501/7d04226a-de14-47a1-934f-979f6bc78406)

**Comment by josepg-limit** [comment]
No hem pogut reproduir l'incidència. Hem provat amb diferents navegadors (Chrom, Firefox, Edge), diferents mides de finesta, diferents sistemes operatius (Windows i Linux)...
