### ISSUE TITLE
Afegir el nom de l'element al missatge d'actualització

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1456]
Quan crees, modifiques o esborres un element (procediment, grup, entitat,...) apareix el missatge: 
`El <element> s'ha creat correctament.`
`El <element> s'ha modificat correctament. `
`El <element>s'ha esborrat correctament.`

S'hauria d'afegir-hi el nom de l'element
`El <element> <nom> s'ha creat correctament.`
`El <element> <nom> s'ha modificat correctament. `
`El <element> <nom s'ha esborrat correctament.`

![image](https://github.com/GovernIB/ripea/assets/58417501/3237703c-7502-445f-b1d5-da84e00bef6b)

**Comment by acuevas-dgtic** [comment]
No apareix el número de registre al acceptar una anotació

Expedient [prova](https://se.caib.es/ripea/contingut/1611881) creat des de l'anotació {2}

**Comment by sandreu-limit** [comment]
S'ha revisat aquest missatge, i hi havia una cometa simple sobrant, la qual causa que no es substitueixin correctament les variables que venen despres de la cometa simple.
S'ha fet una cerca dins el document de traduccions d'altres missatges que podien tenir el mateix problema i s'han canviat.

**Comment by sandreu-limit** [comment]
![Image](https://github.com/user-attachments/assets/6aa0da62-639b-4808-ac83-9e9aeb659592)
