### ISSUE TITLE
Els administradors d'òrgan han de poder modificar el grup d'una anotació del seu òrgan i descendents

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1464]
Pareix que aquesta opció només está disponible per a usuaris administradors d'entitat

![image](https://github.com/GovernIB/ripea/assets/58417501/c58e9b5f-cb34-4859-83fb-316d931f25ee)

**Comment by josepg-limit** [comment]
Relacionada amb [https://github.com/GovernIB/ripea/issues/1471]
