### ISSUE TITLE
Els administradors d'òrgan han de tenir accés a totes les anotacions del seu òrgan i descendents

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1465]
Hem detectat casos d'anotacions associades a un procediment que té la configuració de grups activa i que han arribat sense grup. En aquests casos, els administradors d'òrgan l'haurien de poder consultar i modificar per assignar-li un grup (relacionada amb #1464)

**Comment by josepg-limit** [comment]
Relacionada amb [#1471]
