### ISSUE TITLE
Si envies un document al portafirmes i a continuació canvies el nom del document, desapareix l'estat de l'enviament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1470]
![image](https://github.com/GovernIB/ripea/assets/58417501/a533067a-31c0-4934-a609-8ec047f2a35f)

![image](https://github.com/GovernIB/ripea/assets/58417501/0fbe7af7-feb7-4b51-b1ec-a439a1bcc525)

**Comment by josepg-limit** [comment]
Relacionada amb [#1471]
