### ISSUE TITLE
Permetre esborrar, activar i desactivar avisos de forma massiva

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1500]
Permetre seleccionar.

![image](https://github.com/GovernIB/notib/assets/58417501/49f49416-386f-4268-8637-7728b0c859b6)

**Comment by sandreu-limit** [comment]
![Image](https://github.com/user-attachments/assets/3d44916b-3384-4662-bcc7-b8c75f44750c)
