### ISSUE TITLE
Ordenar alfabèticament la llista de procediments en els filtres i selectors

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1502]

**Comment by acuevas-dgtic** [comment]
No va bé

![Image](https://github.com/user-attachments/assets/9e6bd85a-a548-4a3e-9560-4e62c28631c6)

**Comment by sandreu-limit** [comment]
S'han modificat les funcions de create i update de procediment, per llevar espais en blanc al inici del nom. Que provocava comportaments no desitjats en la ordenació.
A part es prepara un script per actualitzar els noms dels ja existents.
