### ISSUE TITLE
Actualitzar la llibreria de conversió de documents

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1514]
Actualitzar la versió de la llibreria de XdocReport a la seva darrera versió. Actualment la versió 2.0.5

**Comment by sandreu-limit** [comment]
La versión mas alta que se ha podido configurar para la libreria xdocReports para conversión de documentos es la 2.0.2 (anteriormente 1.0.6), ya que posteriores versiones dependen de las librerias xml-beans y apache-poi que requieren de Java8 y la aplicación da errores al desplegar.
