### ISSUE TITLE
Nou sistema de priorització d’expedients

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1516]
Aquest sistema es basarà en un conjunt d'estats de prioritat predefinits, que inclouran BAIXA, NORMAL, ALTA i MOLT ALTA. La prioritat dels expedients es podrà definir en el formulari de creació dels expedients, permetent als usuaris especificar la importància relativa de cada expedient abans de la seva creació. També es permetrà la seva modificació en qualsevol moment posterior.

La prioritat dels expedients es visualitzarà de manera destacada en el llistat d'expedients. Es crearà una nova columna de prioritat que s'afegirà al llistat d'expedients, mostrant el nivell de prioritat de cada expedient.

Cada nivell de prioritat es representarà mitjançant un color específic associat a l'estat corresponent (BAIXA, NORMAL, ALTA i MOLT ALTA), permetent als usuaris identificar ràpidament la prioritat de cada expedient. Es podrà ordenar el llistat d’expedients per aquesta nova columna. S'ha de revisar com afecta aquest color als colors de l'estat

**Comment by josepg-limit** [comment]
Aquesta tasca ha portat més feina de l'esperat degut a que s'han realitzat totes aquestes subtasques:
- Crear nou sistema de prioritats
- Mostrar prioritat en el llistat d'expedient
- Mostrar prioritat a la informació de l'expedient
- Permetre editar la prioritat:
   - Des del llistat d'expedients
   - Des de l'expedient
   - Com a acció massiva
- Permetre definir prioritat al acceptar anotacions
- Mostrar la columna de prioritats als llistats d'accions massives per canviar l'estat i tancar expedients
- Arreglar algun problema amb l'ordenació de columnes en els llistats d'expedinets i d'accions massives per canviar l'estat i tancar expedients

També cal tenir present que s'ha revisat com mostrar els colors dels estats i les prioritats als llistats, ja que emplenar les columnes

**Comment by acuevas-dgtic** [comment]
Habría que añadir un campo extra de motivación cuando la prioridad no sea la normal.

El artículo 71 de la Ley 39/2015 dice lo siguiente:

**Artículo 71. Impulso.**
```
1. El procedimiento, sometido al principio de celeridad, se impulsará de oficio en todos sus trámites y a través de medios electrónicos, respetando los principios de transparencia y publicidad.

2. En el despacho de los expedientes se guardará el orden riguroso de incoación en asuntos de homogénea naturaleza, salvo que por el titular de la unidad administrativa se dé orden motivada en contrario, de la que quede constancia.

El incumplimiento de lo dispuesto en el párrafo anterior dará lugar a la exigencia de responsabilidad disciplinaria del infractor y, en su caso, será causa de remoción del puesto de trabajo.

3. Las personas designadas como órgano instructor o, en su caso, los titulares de las unidades administrativas que tengan atribuida tal función serán responsables directos de la tramitación del procedimiento y, en especial, del cumplimiento de los plazos establecidos.
```

**Comment by sandreu-limit** [comment]
S'ha afegit un camp de motiu de canvi de prioritat, a les pantalles de nou expedient, modificar expedient i al acceptar una anotació, que será obligatori emplenar en cas de que s'hagi indicat una prioritat per l'expedient diferent a la normal.
