### ISSUE TITLE
Permetre tancar un expedient encara que hi hagi remeses tipus comunicació no finalitzades 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1525]
Tenemos expedientes que no podemos cerrar porque tienen  comunicaciones enviadas que no finalizarán nunca. Habría que permitir cerrar el expediente igualmente, ya que las comunicaciones no expiran y no hay previsión de que los interesados comparezcan.

En el caso que el expediente se cierre y llegué un cambio de estado se debe actualizar el estado de la remesa en RIPEA. Dado que las comunicaciones no tienen certificación, no debería dar problemas el archivo digital.

**Comment by acuevas-dgtic** [comment]
S'ha donat el cas d'un expedient amb una notificació (no comunicació) on surt aquest missatge

![image](https://github.com/user-attachments/assets/058e7d01-749f-4af7-8ca5-2c178fd1efbf)

![image](https://github.com/user-attachments/assets/b818be6e-4489-4fc0-8ad6-311a1f9952ff)

**Comment by sandreu-limit** [comment]
S'ha revisat la condició de notificació caducada afegint l'estat. Ara:

- Notificació no caducada i no finalitzada: Error de validació del expedient "Existen notificaciones con un estado que no es final" --> No permet finalitzar.
- Notificació caducada i no finalitzada: No hi ha errors de validació, permet finalitzar amb missatge de intent d'actualització d'estat.
- Notificació caducada i finalitzada: No hi ha errors de validació, permet finalitzar sense missatge.
