### ISSUE TITLE
Poder modificar la data límit d'una tasca

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1527]
Poder modificar la data límit d'una tasca. I que això avisi als responsables.

**Comment by acuevas-dgtic** [comment]
Els camps duració i data límit haurien de ser dependents. No carrega la data límit

![Image](https://github.com/user-attachments/assets/6543bd9d-452f-4d51-bdfe-d2433e466e1c)

**Comment by sandreu-limit** [comment]
La duració d'una tasca al configurar-la al procediment, s'inicialitzará amb un valor per defecte parametritzat, pero es podra deixar a null, igual que passava amb la data límit.

Al crear una tasca per un expedient, s'agafen els valors configurats al procediment. Es poden canviar dant la duració com la data límit, actualtizant-se mutuament de forma automàtica:

![Image](https://github.com/user-attachments/assets/10f48f1e-4c1b-4a95-b767-a2a88c57f8a4)

Es prepara un script per actualitzar la durada de les tasques que actualment tenen data limit definida al valor correcte.
