### ISSUE TITLE
Fer que el procés d'importació des d'un fitxer pugui actualitzar un procediment existent

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1530]
Pareix que només permet importar un procediment nou.

**Comment by sandreu-limit** [comment]
Es podrà seleccionar opcionalment un procediment existent des de la modal de impotació. Si no es selecciona cap funcionarà com la importació actual (mode creació), sino, s'actualitzarà el procediment seleccionat.

En el cas dels elements fills durant la actualització de un procediment (documents, metaDades, estats, tasques, etc): si existeix un element amb el mateix codi, s'actualitzarà, sino es crearà.

En principi no s'eliminarà cap element del procediment que s'està actualitzant.

S'actualitzarà el manual de'administradors.

**Comment by sandreu-limit** [comment]
Actualitzat el manual d'administradors.
