### ISSUE TITLE
Permetre reobrir una tasca

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#1535]
Permetre reobrir una tasca finalitzada i assignar-la a l'usuari original. Es podrà afegir un comentari per a la reobertura, i s'enviarà un correu d'avís a l'usuari original.

**Comment by acuevas-dgtic** [comment]
Si la tasca está finalitzada, no ha d'aparèixer l'acció finalitzar

![Image](https://github.com/user-attachments/assets/3ec529e0-80b1-411c-8931-082b81c21edb)
