### ISSUE TITLE
Omplir automàticament el camp "Identificador ENI del document origen" de l'escaneig

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1542]
El format del camp "Identificador ENI del document origen" del plugin d'escaneig ve imposat per la [NTI del Document electrònic](https://www.boe.es/diario_boe/txt.php?id=BOE-A-2011-13169):

```
Format: ES_<Órgano>_<AAAA>_<ID_específico>
Codificación del Identificador del documento:

<Órgano>: Véase codificación del metadato «Órgano». En caso de más un órgano los nueve caracteres correspondientes serán acordados entre las partes con el fin de asegurarla unicidad del identificador que es su único fin.

<AAAA>: Año de la fecha de captura del documento. (Longitud: 4 caracteres).

<ID específico>: Código alfanumérico que identifica de forma única al documento dentro de los generados por la administración responsable. Cada administración puede diseñar el proceso de generación según sus necesidades, asegurando en cualquier caso su unicidad. Por lo tanto, este ID puede generarse de forma secuencia) o bien, ser una réplica del ID utilizado a nivel interno de la administración. (Longitud: 30 caracteres).
```

Aquest camp s'hauria d'omplir automàticament donat la dificultat d'omplir-lo per part d'un usuari final tal i com està actualment. 
<Órgano>: Codi dir3 de l'òrgan del expedient.
<AAAA: L'any actual durant el procés d'escaneig.
<ID_específico> es pot generar des del codi Hash del document

![image](https://github.com/user-attachments/assets/2d3d481d-289a-433e-898c-ca639fef87fe)

**Comment by sandreu-limit** [comment]
No se ha implementado, pues si el documento es una copia, en el campo "Identificador ENI del documento original" se debe indicar el identificador ENI de donde proviene la copia, no es un campo que se deba generar de manera automática, pues no seria un dato real.
