### ISSUE TITLE
Mostar informació de l'endpoint al monitor d'integracions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1544]
Al monitor no tenim opció per veure l'endopoint del sistema monitoritzat; Aixó pot ser un problema si, per exemple, tenim configurats Portafirmes diferents en funció de l'entitat o l'òrgan. Aquesta informació s'hauria de mostrar de forma detallada al detall de cada entrada i de forma resumida en el llistat. Per aquesta darrera opció, és probable que sigui necessari definir un nom a més del valor de la propietat.

**Comment by sandreu-limit** [comment]
S'ha afegit una propietat "endpointName" que s'ha de configurar per cada un dels plugins que fan peticions externes.
Si no es Configura, intentará mostrar la URL del servei.
