### ISSUE TITLE
S'ha tancat un expedient amb errors de validació de manca de documents

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1546]
El sistema no hauria d'haver permés tancar l'expedient

![image](https://github.com/user-attachments/assets/bc8f8e1b-bde2-4b57-979a-32f503ed4dd2)

**Comment by sandreu-limit** [comment]
Inicialment, un expedient amb errors de manca de documentació no es pot tancar. Apareix el botó deshabilitat, i si intentes obrir la modal per URL manualment, també es fa una validació extra en el métode tancar del servei.
L'error era degut a que no s'actualitzava la cache de errors de validacio del expedient al borrar un document, així que podies afegir els documents obligatoris, despres eliminar-los, i seguidament tancar l'expedient.
Això esta solventat, a part de que, relacionat amb això, al finalitzar l'expedient, els documents obligatoris no signats, no es poden deixar desmarcats, s'han de quedar a l'expedient amb firma en servidor obligatoriament.
