### ISSUE TITLE
No funciona l'enllaç a ConCSV des dels detalls d'un document 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1547]
Exemple: https://se.caib.es/ripea/contingut/1548846. En canvi, sí funciona el botó de descàrrega de versió imprimible.

**Comment by sandreu-limit** [comment]
EL problema era que es pintava l'enllaç, inclusive quant el document no tenia informació del codiCSV (ja que la firma no es de tipus CSV, sino LTV. Ara no apareixerá la fila corresponent al camp CSV de la firma si aquest no existeix, com ja s'esta fent correctament a la taula superior, corresponent a les dades del document.
