### ISSUE TITLE
Revisar acció de reintentar guardar a l'arxiu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1574]
No retorna al llistat de contingut, sino a una pantalla que sembla modal pero es mostra a pantalla completa i no permet tornar enrera.

**Comment by sandreu-limit** [comment]
S'ha revisat la pantalla de retorn en cas de reintentar guardar un document a arxiu desde:
- Un expedient
- Una carpeta
- Una tasca
- El llistat de contingut pendent d'arxiu (administrador)

S'ha detectat i corregit un error que es produia al accedir a tramitar una tasca que tenia un document sense uuidArxiu.
