### ISSUE TITLE
Enviar el codi uuid d'arxiu en lloc del codi CSV en els enviaments a Notib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1577]
S'ha detectat que els documents nous en Alfresco trigen un temps en poder ser accedits per codi CSV. Aixó provoca en Notib que els documents no es pugin notificar en un primer intent i s'hagi de reintentar vàries vegades. Per evitar aixó, l'equip d'arxiu ens recomana enviar el codi uuib d'arxiu a Notib en lloc del CSV.

**Comment by sandreu-limit** [comment]
Enviar el uuid del arxiu que es notifica pareix que es la opció per defecte de RIPEA, es possible que sigui Notib el que intenti obtenir la versió imprimible del document.

![Image](https://github.com/user-attachments/assets/ac354619-7136-44db-8f2b-9ac5ad4f99e6)

![Image](https://github.com/user-attachments/assets/99bcc0f5-015a-4b25-95cf-92a064da7f79)

En cas de zips que contenen varis documents, s'envia a notib el contingut en Base64 del fitxer zip en lloc del uuid.
En cap cas el codi CSV.
