### ISSUE TITLE
Permetre descarregar massivament la versió imprimible dels documents d'un expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1589]
L'acció descarregar documents d'un expedient descarrega en un ZIP la versió original dels documents de l'expedient. S'hauria d'afegir una segona opció per permetre descarregar la versió imprimible dels documents.

**Comment by sandreu-limit** [comment]
Implementada modal para configurar la exportación a ZIP de los documentos de varios expedientes:

![Image](https://github.com/user-attachments/assets/c5f9ab28-d9a1-4025-aae9-5c94e43f702d)

**Comment by sandreu-limit** [comment]
Desde la modal de exportación a ZIP se pueden configurar algunas opciones de la exportación. Una vez se pulsa el botón "Exportar", se prepara un proceso en segundo plano, que se ejecutará el algún momento posterior, i que se podrá consultar desde el seguimiento de acciones masivas, desde donde también se podrá descargar el documento.

![Image](https://github.com/user-attachments/assets/743eb186-5de7-4ff1-95f9-9a2c01206820)
