### ISSUE TITLE
Problema per previsualitzar un document PDF

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1593]
Hi ha usuaris que no poden previsualitzar el contingut d'un document PDF. EL surt un missatge de confirmació per sortir de la pàgina.  Jo no he estat capaç de reproduir-lo amb Chrome, Firefox ni amb Edge.

**Comment by sandreu-limit** [comment]
Desde la versión anterior de RIPEA, se utilizan los visores que incorporan los propios navegadores en lugar de una librería externa, por ser una opción mas fiable y óptima.
Firefox tiene ciertas restricciones y comportamientos específicos al cargar PDFs en iframes, lo que puede causar que el navegador solicite confirmación antes de salir de la página.
Probar de cambiar la configuración de Firefox para que utilice el visor de PDF integrado para abrir tipos de ficheros PDF en lugar de la opción de preguntar o visor externo (que podría requerir tener Adobe Reader instalado).

![Image](https://github.com/user-attachments/assets/e1b6c06e-9e56-484f-ad16-128e95d49f28)

**Comment by sandreu-limit** [comment]
Solventat després de recomanar una actualització del Navegador.
