### ISSUE TITLE
Revisar l'acció alliberar expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1598]
Tenc 21 expedientes que vull alliberar però no puc perquè no som la persona que va agafar l'expedient inicialment. El problema és que la persona que va agafar l'expedient ja no fa feina amb noltros. Com ho puc fer per  alliberar l'expedient i que no quedi associat a cap persona?

------
Quan l'alliber torna a la persona que el va agafar per primera  vegada però aquesta persona ja no fa feina amb noltros i voldria que els expedients no quedassin agafats per ningú. Com ho podria fer?

**Comment by sandreu-limit** [comment]
Podem afegir una opció de "Anular assignació" que faci exactament això, deixar a null el usuari de un expedient, en lloc de tornar al usuari anterior. Si vos pareix correcte. @acuevas-dgtic

**Comment by acuevas-dgtic** [comment]
La lògica diu que l'acció "Alliberar" ha de deixar l'expedient sense asignar. Per exemple, les tasques d'Helium es comporten així. Crec que millor que hi hagi dues accions:
-Allibera:  sense assignar.
-Retorna al gestor anterior.

**Comment by sandreu-limit** [comment]
S'han implementat dues funcionalitats separades:

Alliberar - Deixa el expedient sense assignació
Retornar - Torna l'expedient al gestor que el va crear (antiga funcionalitat de alliberar)

Actualitzat el historial de accions del expedient per contemplar la nova acció.
