### ISSUE TITLE
Permetre configurar metadades ENI per defecte als tipus de document

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#231]
En el cas dels en que el document sigui un document definit per defecte al tipus  d’expedient, hauria d’agafar les metadades eni associades al document de manera automàtica.

En el cas que es crea un document, ara mateix, s’estan informant per defecte tots els valors ENI/NTI amb un valor per defecte que no té molt de sentit, seria millor deixar-ho en blanc excepte la data de captura que es podria omplir automàticament com ara i l’òrgan que per defecte podria agafar el del tipus d’expedient. Els altres valors els deixaria en blanc per obligar a l’usuari a emplenar-los.

**Comment by acuevas-dgtic** [comment]
Esta funcionalidad está implementada
