### ISSUE TITLE
 Igualar comportament del NOTIB al enviar notificacions des de RIPEA

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#343]
Quan es crea una notificació des de RIPEA:
![image](https://user-images.githubusercontent.com/17267008/67836588-5282ae80-faed-11e9-97fe-5b6c231cd222.png)
Hauria de permetre totes les opcions que es permeten des de NOTIB, les mateixes.
A NOTIB (que equival a Notific@) cada notificació pot tenir N enviaments (que són tothom que la
pot rebre), i és a cada enviament on podem indicar:
• tipus: normal / urgent
• titular
• N destinataris (amb el tipus d’interessat que és cada un d’ells)
• entrega postal (un checkbox que si està activat, es desplega i es pot indicar l’adreça postal)
![image](https://user-images.githubusercontent.com/17267008/67836605-5c0c1680-faed-11e9-9a80-d09983a5a492.png)

**Comment by acuevas-dgtic** [comment]
En conformidad con la Ley 39/2015 (art 40, 41, 43) hay que tener en cuenta lo siguiente:

- Si solo hay un interesado, éste será el titular de la notificación.
- Si hay más de un interesado, se deberá enviar una notificación independiente para cada uno (no varios envios de la misma notificación). Para cada notificación, el interesado será el titular de la misma.
- Si el interesado tiene representante, el interesado seguirá siendo el titular de la notificación; se añadirá el representante a la lista de destinatarios.
