### ISSUE TITLE
Millores en la pantalla de gestió de l'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#365]
- [ ] A la part superior posar com a títol el nombre de l'expedient seguit del títol de l'expedient.
- [ ] Donar més rellevància als estats dels expedients.
- [ ] #544  Proporcionar informació sobre els darrers esdeveniments i accions realitzades sobre l'expedient.
- [ ] Avaluar quina informació s'ha de mostrar en el quadre gris de l'esquerra.

**Comment by acuevas-dgtic** [comment]
issue antiga
