### ISSUE TITLE
Adaptació de RIPEA per gestionar procediments comuns

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#394]
S’ha d’adaptar el funcionament de RIPEA per tal que pugui gestionar procediments comuns. Es a dir, una tipologia d’expedient ha de poder ser gestionada per grups de gent diferents que pertanyen a òrgans gestors diferents.

**Comment by acuevas-dgtic** [comment]
Aquesta issue depèn de #494

**Comment by josepg-limit** [comment]
Modificarem el formulari de creació/modificació del tipus d'expedient per a incorporar un nou camp de tipus select que permeti indicar si el procediment és comú a tots els òrgans de l'entitat o si pertany a un òrgan gestor.
El camp per a indicar l'òrgan gestor haurà de ser opcional i només apareixerà si al deseplegable seleccionam que el tipus d'expedient pertany a un òrgan gestor.

**Comment by acuevas-dgtic** [comment]
El camp desplegable "Gestor del tipus d'expedient" no és adequat. Hauria d'haver un check opcional que digui "Tipus d'expedient comú". A més, a la gestió de tipus d'expedient, el filtre 'Veure registres sense òrgan gestor ' hauria de dir "Veure tipus d'expedients comuns"
