### ISSUE TITLE
Conversió de documents esborranys a definitius

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#406]
A la DGMAD li agradaria d'alguna manera, que entenc que es podria arribar a fer configurant per property (encara no ho tenen clar i ja us ho indicarien ells), que quan l'expedient es tanqui, els esborranys poguessin passar-se a definitius, segellar amb CADES i així arxivar. Però ja us dic, és una idea que tenen, que de moment no s'implementaria en ripea, i que entenem que es podria fer per Property.

**Comment by acuevas-dgtic** [comment]
Duplicat Gestió dels esborranys al tancar expedients #431 . Si l'expedient es tanca, l'usuari decidirà què vol fer: esborrar l'esborrany o firmar-lo en servidor
