### ISSUE TITLE
Revisar hora de la data d'obertura d'un expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#415]
Quan es crea un nou expedient, la hora del camp "Data d'obertura" apareix sempre a 00:00:00

**Comment by josepg-limit** [comment]
Això és perquè aquesta data s'obté de l'arxiu que sempre retorna les hores minuts i segons amb el valor 0.
Per a evitar solucionar el problema farem que es mostri la data d'obertura amb el format 'dd/MM/yyyy'.

**Comment by acuevas-dgtic** [comment]
No, la NTI del expediente-e dice que hay que poner la hora. Parece un bug de ARXIU https://github.com/GovernIB/gdib/issues/33

**Comment by acuevas-dgtic** [comment]
Más que un bug de Arxiu parece un bug del pulgin de Arxiu

**Comment by josepg-limit** [comment]
Hem fet una prova del plugin d'arxiu imprimint els missatges que s'envien i reben de l'arxiu digital. Els resultats han estat els següents:

- PETICIO:
--------------
{
	"createFileRequest": {
		"serviceHeader": {
			"serviceVersion": "1.0",
			"auditInfo": {
				"application": "ARXIUTEST"
			},
			"securityInfo": {
				"user": "app1",
				"password": "app1"
			}
		},
		"param": {
			"file": {
				"name": "ARXIUAPI_prova_exp_1594133606782",
				"type": "eni:expediente",
				"metadataCollection": [
					{
						"qname": "eni:origen",
						"value": "1"
					},
					{
						"qname": "eni:cod_clasificacion",
						"value": "S0001"
					},
					{
						"qname": "eni:id_tramite",
						"value": "organo1_PRO_123456789"
					},
					{
						"qname": "eni:estado_exp",
						"value": "E01"
					},
					{
						"qname": "eni:organo",
						"value": [
							"A04013511"
						]
					},
					{
						"qname": "eni:interesados_exp",
						"value": [
							"12345678Z",
							"00000000T"
						]
					},
					{
						"qname": "eni:fecha_inicio",
						"value": "2020-07-07T14:53:26.785Z"
					}
				],
				"aspects": [
					"eni:interoperable",
					"eni:transferible"
				]
			},
			"retrieveNode": "true"
		}
	}
}

- RESPOSTA:
-------------------
{
	"createFileResult": {
		"result": {
			"code": "COD_000",
			"description": "Petición realizada correctamente."
		},
		"resParam": {
			"id": "43b03957-e4fc-4f31-8a3e-87a06b6f5db9",
			"type": "eni:expediente",
			"name": "ARXIUAPI_prova_exp_1594133606782",
			"aspects": [
				"eni:interoperable",
				"eni:transferible"
			],
			"metadataCollection": [
				{
					"qname": "eni:id_tramite",
					"value": "organo1_PRO_123456789"
				},
				{
					"qname": "eni:origen",
					"value": 1
				},
				{
					"qname": "eni:v_nti",
					"value": "http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e"
				},
				{
					"qname": "eni:organo",
					"value": "A04013511"
				},
				{
					"qname": "eni:fase_archivo",
					"value": "Archivo activo"
				},
				{
					"qname": "eni:soporte",
					"value": "Digital"
				},
				{
					"qname": "eni:cod_clasificacion",
					"value": "S0001"
				},
				{
					"qname": "eni:interesados_exp",
					"value": [
						"12345678Z",
						"00000000T"
					]
				},
				{
					"qname": "eni:id",
					"value": "ES_A04013511_2020_EXP_qcpibd450g6sijrn8d4bikvf7ie5us"
				},
				{
					"qname": "eni:app_tramite_exp",
					"value": "app1"
				},
				{
					"qname": "eni:estado_exp",
					"value": "E01"
				},
				{
					"qname": "eni:categoria",
					"value": "Expediente"
				},
				{
					"qname": "eni:fecha_inicio",
					"value": "2020-07-07T00:00:00.000+02:00"
				},
				{
					"qname": "eni:lopd",
					"value": "Basico"
				},
				{
					"qname": "eni:tipo_acceso",
					"value": "Libre"
				},
				{
					"qname": "eni:cond_reutilizacion",
					"value": "fdddf"
				},
				{
					"qname": "eni:tipo_valor",
					"value": "Administrativo"
				},
				{
					"qname": "eni:plazo",
					"value": 222
				},
				{
					"qname": "eni:tipo_dictamen",
					"value": "ET"
				},
				{
					"qname": "eni:accion_dictaminada",
					"value": 100
				},
				{
					"qname": "eni:plazo_accion_dictaminada",
					"value": 1
				},
				{
					"qname": "eni:tipo_clasificacion",
					"value": "SIA"
				}
			]
		}
	}
}

Segons això la petició enviada a l'arxiu és correcta i conté la data amb hores minuts i segons. Però a la resposta de l'arxiu la data es retorna truncada, la qual cosa indica que el truncament es produeix a l'arxiu.

**Comment by acuevas-dgtic** [comment]
He observado que sí aparece la hora en los metadatos de la ventana de información del archivo pero no en la página principal del expediente
![imatge](https://user-images.githubusercontent.com/58417501/86882749-0878b080-c0f1-11ea-989d-e785f36f8d9f.png)

**Comment by acuevas-dgtic** [comment]
Dejamos esta incidencia pendiente hasta que se solucione el tema en el archivo

**Comment by acuevas-dgtic** [comment]
Solucionado en DEV y PRE. Depende de la versión de Alfresco para que se active en PRO. No es un tema de RIPEA
