### ISSUE TITLE
El camp de municipi surt buid

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#417]
Quan afegeixes un interessat tipus: administració, el camp municipi surt buid i tampoc te deixa omplir-ho

**Comment by josepg-limit** [comment]
El camp municipi s’omple automàticament amb el camp descripcionLocalidad de l'unitat organitzativa obtinguda en una consulta a DIR3CAIB.
Hem comprovat que, de vegades, quan escollim alguna unitat organitzativa des de l'entorn de proves, el camp descripcionLocalidad es retorna com amb el valor null.
Podria ser perquè les dades que retorna DIR3CAIB als entorns de dev o proves son incompletes?
