### ISSUE TITLE
Gestió dels esborranys al tancar expedients

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#431]
La problemàtica actual és que, al tancar un expedient a l'arxiu de la CAIB, els documents de tipus esborrany s'eliminen de l'expedient i això provoca inconsistències entre RIPEA i l'arxiu perquè a l'arxiu els documents no existeixen mentre que a RIPEA si.

Per a evitar aquest problema, RIPEA no deixa tancar un expedient si aquest conté esborranys.

Aquesta restricció s'hauria d'eliminar i permetre als usuaris tancar l'expedient maldament aquest contengui esborranys.

En la versió actual de RIPEA, ll tancar un expedient, apareix una pantalla per a introduir els motiu de tancament. Aquesta pantalla s'hauria de modificar per a mostrar informació addicional si l'espedient que es vol tancar conté esborranys. En aquest cas s'hauria de mostrar un llistat dels esborranys de l'expedient i permetre seleccionar als usuaris què volen fer amb aquests documents.
Les opcions disponibles son:
1.- Esborrar el document de l'expedient.
2.- Firmar el document amb firma de servidor per a que aquest document es conservi una vegada tancat l'expedient.

En qualsevol cas, hauràn de mostar-se texts explicatius a l'usuari per a informar-lo clarament de les implicacions de les seves accions.

**Comment by josepg-limit** [comment]
Aquesta issue depen de #482

**Comment by josepg-limit** [comment]
El desenvolupament d'aquesta issue es dona per acabat, però la deixam sense tancar a falta de proves a l'entorn de desenvolupament de la CAIB.

**Comment by josepg-limit** [comment]
Donam aquesta issue per finalitzada però no la tancarem perquè s'ha de provar a l'entorn de DEV de la CAIB.

**Comment by acuevas-dgtic** [comment]
Al intentar cerrar un expediente con un borrador aparece la pantalla de firma en servidor pero al seleccionarlo da error

![imatge](https://user-images.githubusercontent.com/58417501/93314889-aaf89280-f80a-11ea-8d6b-a5234cba285c.png)
