### ISSUE TITLE
Tipus de flux de firma Simple: No results found 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#439]
No es pot definir un tipus de flux de firma simple. El camp Responsable no mostra cap resultat.

**Comment by acuevas-dgtic** [comment]
Esta propiedad ya estaba configurada en RIPEA pero el error persiste

**Comment by josepg-limit** [comment]
Hemos arreglado el error que hemos detectado con los responsables de firma que ya no existen y lo hemos incluido en la solución de esta incidencia.

Para que la aplicación filtre por DNI hay que modificar la propiedad  es.caib.ripea.plugin.dades.usuari.jdbc.query.filtre para incluir una condición que filtre por la columna nif.
