### ISSUE TITLE
Revisió de literals de fluxos de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#443]
S'hauria de canviar el literal 'Tipus de flux de firma' per 'Tipus de firma' amb els següents valors: "Simple" i "Plantilla de flux de firmes"

**Comment by acuevas-dgtic** [comment]
Siguen apareciendo los literales antiguos

**Comment by josepg-limit** [comment]
Hi havia missatges de traduccions duplicats

**Comment by acuevas-dgtic** [comment]
Sigue apareciendo el literal "Portafib". Ha de poner "Plantilla de flux de firmes"
