### ISSUE TITLE
Error amb Firma amb passarel·la

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#449]
He provat d'adjuntar un document word i firmar-lo amb  "Firma amb passarel·la" (proposaria un canvi de nom) i el popup de Portafib no es tanca una vegada finalitzada la signatura client. 
Tot i això RIPEA informa que el document no es pot signar i me queda en estat d'esborrany.

**Comment by acuevas-dgtic** [comment]
Per provar que no fos cosa de la conversió del document he afegit un altre document directament en PDF i també m'ha petat

**Comment by acuevas-dgtic** [comment]
Sigue quedándose la pantalla en blanco y no hace nada

**Comment by acuevas-dgtic** [comment]
Hay que actualizar la página para ver el documento firmado

**Comment by josepg-limit** [comment]
Era un problema del javascript para cerrar la ventana. Ahora ya debería funcionar.
