### ISSUE TITLE
Error AJAX: [0] abort al afegir responsables de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#452]
A l'hora d'afegir/cercar un responsable de firma amb portafirmas apareix l'error: Error AJAX: [0] abort 

![imatge](https://user-images.githubusercontent.com/58417501/84654556-b4bee100-af0f-11ea-9bcf-29a0d56a06de.png)

Si polsam el botó 'D'acord' desapareix la finestra d'error i mostra el llistat de responsables filtrats, però s'ha de evitar mostrar aquest error.

**Comment by josepg-limit** [comment]
Per a reproduir el problema s'ha de:
- Anar a Gestió de tipus d'expedients > Tipus de documents > Nou tipus de document
- Activar pipella Firma amb portafirmes
- Activar camp "Forma amb portafirmes activa"
- Introducir al menos 4 caracteres (ejemplo '4312') en el campo Responsables

**Comment by josepg-limit** [comment]
Hem capturat l'excepció per a evitar que torni a sortir l'error i hem fet que surti la traça als logs.

**Comment by acuevas-dgtic** [comment]
Sigue apareciendo este error al buscar por NIF (no por nombre). En teoría, el valor de la variable es.caib.ripea.plugin.dades.usuari.jdbc.query.filtre está bien definido 

es.caib.ripea.plugin.dades.usuari.jdbc.query.filtre=select usu_codi, usu_nom, usu_nif, usu_codi||'@caib.es' from sc_wl_usuari where lower(usu_nom) like lower('%'||:filtre||'%') or lower(usu_nif) like lower('%'||:filtre||'%')

**Comment by acuevas-dgtic** [comment]
Este error también aparece en la lista de Responsables de una tarea. Solo deja buscar por nombre

**Comment by josepg-limit** [comment]
Per a reproduir aquest error s'ha de fer el següent:
1.- Introduir 3 caràcters al camp per a disparar la cerca.
2.- Esperar un moment (uns 500 ms).
3.- Introduir un caràcter addicional al camp.

Això fa que es torni a enviar una nova petició AJAX per a consultar els usuaris i, en determinades ocasions, el navegador fa que es cancel·li la petició anterior que retorna un error.
Aquest error és el que apareix a l'alerta Javascript: status=0, statusText='abort'
