### ISSUE TITLE
Missatge d'expedients existents a l'hora d'esborrar un tipus d'expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#460]
Si  es vol esborrar un tipus d'expedient amb expedients ja creats dóna el següent error:
`???org.hibernate.exception.ConstraintViolationException: could not delete: [es.caib.ripea.core.entity.MetaExpedientEntity#11673]??? `

S'hauria de mostra el següent missatge a l'usuari: 
`Aquest tipus d'expedient no es pot esborrar ja que existeixen expedients dependents. Per favor, esborri primer aquests expedients.`

**Comment by acuevas-dgtic** [comment]
A més, s'ha de revisar ja que quan esborres tots els expedients continua mostrant el mateix error.

**Comment by josepg-limit** [comment]
Hem solucionat el problema del missatge d'error. Però els tipus d'expedients que han tengut expedients associats es segueixen sense poder esborrar (els expedients no s'esborren realment de la base de dades), per fer-ho s'hauria d'implementar lògica nova per a gestionar-ho.
