### ISSUE TITLE
Error en crear document

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#467]
Al crear un documento aparece el siguiente error:
org.springframework.dao.IncorrectResultSizeDataAccessException: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements 

![imatge](https://user-images.githubusercontent.com/58417501/85707086-24d52000-b6e3-11ea-89b2-6b87a3b13e1b.png)

![imatge](https://user-images.githubusercontent.com/58417501/85707136-30284b80-b6e3-11ea-8e35-4a25214fda8a.png)

![imatge](https://user-images.githubusercontent.com/58417501/85706945-01aa7080-b6e3-11ea-904e-3619473f6639.png)

![imatge](https://user-images.githubusercontent.com/58417501/85707318-5c43cc80-b6e3-11ea-90cc-a17e9b58b220.png)

**Comment by josepg-limit** [comment]
Este era un problema con la ejecución de los scripts que ha provocado que el contenido de la tabla de tipus de documento estuviera duplicado.

**Comment by acuevas-dgtic** [comment]
Sigue dando problemas en PRE, aunque al final sí se crea el documento

![imatge](https://user-images.githubusercontent.com/58417501/86244867-e343e980-bba8-11ea-8e8e-651541940ead.png)

![imatge](https://user-images.githubusercontent.com/58417501/86244916-fbb40400-bba8-11ea-920c-4ecc7f71ff72.png)

![imatge](https://user-images.githubusercontent.com/58417501/86244962-08d0f300-bba9-11ea-989f-bd444b3ab1f6.png)

![imatge](https://user-images.githubusercontent.com/58417501/86245017-23a36780-bba9-11ea-9276-80b471f0f579.png)
