### ISSUE TITLE
Error en notificar un document

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#469]
Al notificar un document apareix Ajax error i a continuació es mostra una finestra d'autenticació en Notib 

![imatge](https://user-images.githubusercontent.com/58417501/85716160-7a61fa80-b6ec-11ea-8844-30dd7d9b3cc6.png)

**Comment by josepg-limit** [comment]
Pareix que és degut a un error que retorna NOTIB al intentar crear la notificació. Mirarem si és un bug de NOTIB o si hi ha algun problema amb els paràmetres que s'envien.
