### ISSUE TITLE
Afegir opció d'escollir un flux de firma existent a l'hora d'enviar un document al portafirmes

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#480]
Durant el procés d'enviament d'un document al portafirmes de tipus Plantilla de flux, l'usuari ha de tenir també l'opció d'escollir un dels fluxos existents. Actualment només pot crear-ne un de nou o fer servir el que ve per defecte al tipus de document.

**Comment by acuevas-dgtic** [comment]
Da error 500 al enviar al portafirmas

**Comment by josepg-limit** [comment]
Parece un error de configuración del usuario que accede a Portafib. Debido a las nuevas funcionalitades requeridas en la integración con portafib, el usuario de Portafib de RIPEA debe tener acceso al web service /ws/v1/PortaFIBUsuariEntitat y el usuario que se utilitza no debe tener los permisos necesarios.

**Comment by acuevas-dgtic** [comment]
El usuario ya tiene ese rol y sigue dando el mismo error

**Comment by acuevas-dgtic** [comment]
Solucionado. Había un error en la url del callback en Portafib
