### ISSUE TITLE
Actualitzar llibreria de datatables a versió 1.10+ 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#496]
Es fa necessari actualitzar la llibreria de datatables per tal d'evitar que es vagin produint errors de peticions Ajax a l'aplicació, al arribar al límit de capacitat de cookies del navegador.

**Comment by acuevas-dgtic** [comment]
Sigue dando problemas con uan sesión abierta. Se supone que al actualizar al libreria estos errores desaparecerían

![imatge](https://user-images.githubusercontent.com/58417501/94789120-cc45ab00-03d4-11eb-89de-aea57c82613c.png)

**Comment by josepg-limit** [comment]
La versión actual de la librería es la 1.10.19. El error debe de darse por otra causa.
Nos podeis explicar los pasos que seguís para reproducir este error?

**Comment by acuevas-dgtic** [comment]
El error se produce al acceder a la dirección https://dev.caib.es/ripea/expedient. la única forma de que no aparezca es abrir una ventana nueva de incógnito

**Comment by josepg-limit** [comment]
Es un problema con la longitud de la peticion HTTP GET que obtiene información para mostrar en el datatable. Debido a la gran cantidad de parámetros que envian las peticiones de datatables y al tamaño de las cookies, la petición puede exceder fácilmente el máximo configurado en el servidor web que es de 8192 bytes.

Este máximo se puede configurar en JBoss: https://developer.jboss.org/thread/221977

De todas formas intentaremos hacer que las peticiones a datatables no envien tantos parámetros.
