### ISSUE TITLE
Renombrar classificació per Codi SIA

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#502]
A la pantalla principal d'un expedient apareix el literal 'Classificació'; en canvi, a la finestra de disseny del tipus d'expedient aquest camp es diu 'Codi procediment SIA'. El camp s'ha de dir 'Codi SIA' als dos llocs. A la finestra d'informació de l'arxiu s'ha de continuar dient 'Classificació' encara que tingui el mateix valor que el Codi SIA.

![imatge](https://user-images.githubusercontent.com/58417501/86883087-a8363e80-c0f1-11ea-9377-5528d4184e57.png)
![imatge](https://user-images.githubusercontent.com/58417501/86883126-bbe1a500-c0f1-11ea-8754-f9b9918a7853.png)

**Comment by santich-dgtic** [comment]
Modificar tipus exèdient segueix posant "codi procediment SIA"
