### ISSUE TITLE
No s'actualitza el document signat amb plantilla de flux de firmes i firmes externes

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#511]
He firmat externament sense problemes i teòricament finalitzat el flux de firma però RIPEA no ha actualitzat l'estat del document. Segueix com a "Pendent de firmar",

![imatge](https://user-images.githubusercontent.com/58417501/87034776-b024da00-c1e8-11ea-8b4e-99e0abe0da97.png)

Nom de l'expedient: test5
Número: SESSIONS_GTID/12/2020
Entorn: Preproducció

**Comment by acuevas-dgtic** [comment]
Sigue sin resolverse en la 0.9.74.1

**Comment by josepg-limit** [comment]
Aquest problema sí que està resolt però, degut a l'error, el document s'ha quedat en un estat inconsistent perquè està firmat a l'arxiu i sense signar a RIPEA. Això fa que cada vegada que s'intenta tornar a processar el document es produeixi un error perquè s'intenta modificar un document a l'arxiu que ja esta firmat.
