### ISSUE TITLE
Error en esborrar expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#512]
He intentat esborrar un expedient ja creat des del cercador i també m'ha donat error:

![imatge](https://user-images.githubusercontent.com/58417501/87035477-af407800-c1e9-11ea-870e-e5046ac8a474.png)

**Comment by josepg-limit** [comment]
Aquest error pareix provocat per un expedient que es va modificar directament a base de dades. Omb l'operativa "normal" que es fa des de la interfície d'usuari no es donaria aquest error.

**Comment by acuevas-dgtic** [comment]
Continuan los errores
