### ISSUE TITLE
Modificar el peu de pàgina per a mostrar la versió i la data de compilació

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#525]
Modificar la forma en que es calcula el nombre de versió de l'aplicació per a que s'hagi d'especificar directament al fitxers pom.xml del codi font.
Aquest nombre de versió s'haurà de traslladar automàticament, al generar l'arxiu desplegable (ear o war), al fitxer META-INF/MANIFEST.MF conjuntament amb el timestamp de la compilació.

RIPEA haurà de llegir aquesta informació del fitxer MANIFEST.MF i l'haurà de traslladar al peu de la interfície d'usuari. La visualització d'aquesta informació s'ha de fer igual que a l'aplicació DISTRIBUCIO. O sigui, que la data de compilació només s'ha de veure al seleccionar el text de la versió.

**Comment by acuevas-dgtic** [comment]
EL formato no es correcto. Hacer algo similar a https://github.com/GovernIB/notib/issues/311
