### ISSUE TITLE
Generar ZIP amb un índex de l'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#526]
Afegir una opció per generar un zip amb un índex de l'expedient. El zip ha de contenir tots els documents de l'expedient enumerats i un document que serà l'índex on sortirà dins una taula amb el resum de cada document.

Exemple (zip):
![imagen](https://user-images.githubusercontent.com/17267008/87782130-3ddc7700-c832-11ea-968f-159ad089f94b.png)

Exemple (índex):

![imagen](https://user-images.githubusercontent.com/17267008/87782907-b4c63f80-c833-11ea-9f34-d7aad386c9a2.png)

**Comment by acuevas-dgtic** [comment]
En el GOIB neceistamos también añadir esta funcionalidad. En concreto, necesitaremos generar un ZIP con: el XML ENI del Expediente-e + XML del índice del expediente + los N ficheros xml de los documentos en formato ENI. Hay que revisar la NTI del Expediente-e y del Documento-e
