### ISSUE TITLE
Error seguiment d'enviament a portafirmes

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#528]
Si s'ha enviat un document a signar i aquest ha estat signat abans de refrescar la finestra de l'expedient a RIPEA; a l'acció de seguiment d'enviaments a portasignatures del document apareix un error que diu "Aquest document no te enviaments..."

![imatge](https://user-images.githubusercontent.com/58417501/88046850-f830ee80-cb50-11ea-85bb-d5dc123e857e.png)

![imatge](https://user-images.githubusercontent.com/58417501/88046803-e6e7e200-cb50-11ea-87e3-2a581122fee8.png)

**Comment by josepg-limit** [comment]
En aquest cas s'ha de controlar l'excepció i mostrar un missatge a l'usuari que indiqui aquesta situació.
