### ISSUE TITLE
Millorar el seguiment de signatura amb varis signants

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#529]
Si s'ha definit un tipus de firma simple o s'utilitza una plantilla de flux de firmes amb vàries persones, s'ha de mostrar les firmes realitzades i les pendents al seguiment de l'enviament

**Comment by acuevas-dgtic** [comment]
No sé si es un error del código o de configuración pero da un error 500 a la hora de enviar al portafirmas

**Comment by josepg-limit** [comment]
Parece un error de configuración del usuario que accede a Portafib. Debido a las nuevas funcionalitades requeridas en la integración con portafib, el usuario de Portafib de RIPEA debe tener acceso al web service /ws/v1/PortaFIBUsuariEntitat y el usuario que se utilitza no debe tener los permisos necesarios.

**Comment by acuevas-dgtic** [comment]
Se solucionó el error de acceso, sin embargo no se actualiza bien un documento con varias firmas. Si se firma una vez, al consultar el estado en ripea aparece el error "es.caib.ripea.core.api.exception.ValidationException: Aquest document no te enviaments a portafirmes "

**Comment by acuevas-dgtic** [comment]
El cambio de estado sigue sin ir bien. Se cambia el documento a firmado pero después a no firmado
