### ISSUE TITLE
Afegir manual d'usuari 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#531]
Afegir opció de menú per descarregar el manual d'usuari (similar a com està a Distribució)

![imatge](https://user-images.githubusercontent.com/58417501/93306254-e5a8fd80-f7ff-11ea-8bd3-b831919f5707.png)

**Comment by acuevas-dgtic** [comment]
No aparece

**Comment by josepg-limit** [comment]
Hola Asier,
Hemos añadido el manual al código fuente. Pero no hemos añadido el enlace a la aplicación. Ahora lo solucionamos.

**Comment by acuevas-dgtic** [comment]
El manual no está donde hemos puesto en la descripción

**Comment by acuevas-dgtic** [comment]
Está igual que en Notib pero es un diseño disruptivo. Tenemos previsto modificar todas las aplicaciones para que el manual esté debajo de la configuración del usuario
