### ISSUE TITLE
Històric d'accions i esdeveniments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#544]
Mostrar una secció d'històric que mostri informació dels darrers esdeveniments i accions realitzades sobre l'expedient.

**Comment by josepg-limit** [comment]
Aquests esdeveniments inclouran:
- Creació / modificació / eliminació d'elements de l'expedient (documents, carpetes, interessats).
- Events de firma de documents (firma servidor, events portafirmes, firma amb passarel·la).
- Events de notificacions (enviament, rebuig, certificació).

**Comment by josepg-limit** [comment]
La prova dels logs de carpetes no es pot implementar fins que no s'hagi resolt la issue #565
