### ISSUE TITLE
Ha desaparegut l'òrgan gestor de la fitxa del tipus d'expedient

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#572]
No apareix cap opció per configurar l'òrgan gestor del tipus d'expedient

![imatge](https://user-images.githubusercontent.com/58417501/94905182-bbf90300-049c-11eb-9960-6e074b8e7073.png)

**Comment by josepg-limit** [comment]
Això és perquè està activada l'opció "Tipus d'expedient comú"
