### ISSUE TITLE
Canvi d'ordre en responsables portafirmes

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#574]
Un usuari vol enviar un document a signar per varis responsables amb signatura simple en sèrie. Si per exemple en primer lloc escriu un responsable que comenci per Josep i després altre que comenci per Asier, la finestra canvia l'ordre dels signants (pareix que els ordena alfabèticament)

![imatge](https://user-images.githubusercontent.com/58417501/95071537-18ad2580-070a-11eb-9f8c-b2189ccef115.png)

**Comment by josepg-limit** [comment]
Hemos detectatdo que el problema proviene de Portafib al mostrar incorrectamente los firmantes como respuesta a la petición getPeticioDeFirmaWs().getPeticioDeFirma(portafirmesId).

De todas formas, como parte de esta incidencia, cambiaremos la forma en que se muestra el flujo de firma y que el usuario no tenga que apretar el boton para que se muestre.
