### ISSUE TITLE
Problema amb plantilles de flux de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#590]
Continua sense funcionar la definició de documents amb Plantilla de flux de firma. Una vegada guardats els canvis, desapareixen les dades del flux i apareixen els camps responsables i seqüencia de signatura.

Procés:
1. Defineixo les dades generals.
2. Defineixo les dades NTI
3. Defineixo i actiu la signatura amb portafirmes. Selecciona tipus "Plantilla de flux" i m'apareix el llistat de flux de signatures de manera correcta i guardo els canvis.
4. En obrir de nou la configuració el desplegable de fluxos està buit i han aparegut els camps responsables i seqüència de signatura que no haurien d'aparèixer.

![01_dades](https://user-images.githubusercontent.com/58417501/95822793-dd73ad80-0d2c-11eb-8c9a-0f8379145d8e.PNG)
![02_NTI](https://user-images.githubusercontent.com/58417501/95822810-e5cbe880-0d2c-11eb-9825-559b0b0438aa.PNG)
![03_portafirmas](https://user-images.githubusercontent.com/58417501/95822819-e82e4280-0d2c-11eb-9eff-1a6e96502b7b.PNG)
![04_portafirmas_tras_guardar](https://user-images.githubusercontent.com/58417501/95822824-ea909c80-0d2c-11eb-8029-2dfa39883333.PNG)

**Comment by josepg-limit** [comment]
El problema està causat pel nom del tipus de document, que conté una cometa simple. Això fa que es produeixi un error de Javascript i fa que tot funcioni malament.
