### ISSUE TITLE
Mostar flux de firma al desplegable

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#596]
Si un document té un flux de firma predefinit s'ha de mostrar seleccionat al desplegable ja que pareix que no està definit

![imatge](https://user-images.githubusercontent.com/58417501/96689172-548af080-1382-11eb-9ed5-2b7ba3983e11.png)

**Comment by josepg-limit** [comment]
Canvi realitzat en la següent issue:
#588 Millores referents als fluxos de firma
