### ISSUE TITLE
Reassignació d'expedients per codi d'usuari

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#605]
Afegir codi d'usuari al desplegable "Usuari" de la opció "Assignar expedient a usuari" per permetre reassignar per nom i per codi

![imatge](https://user-images.githubusercontent.com/58417501/97274702-4f6fea80-1835-11eb-9cb0-ae66130789cf.png)

**Comment by acuevas-dgtic** [comment]
S'hauria de mostrar entre parèntesis el codi d'usuari en el desplegable per poder verificar-ho
