### ISSUE TITLE
No surten tots els estats al filtre del cercador d'expedients

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#608]
Al cercador d'expedients, només te permet filtrar per dos estats, obert i tancat, però dins aquesta columna també surten estats específics del tipus d'expedient, si surten dins aquesta columna també s'hauria de poder filtrar per ells.

**Comment by acuevas-dgtic** [comment]
Duplicat #571

**Comment by josepg-limit** [comment]
Els estats surten, però per a veure'ls s'ha de seleccionar abans un tipus d'expedient. Això és degut a que els estats estan associats a un tipus d'expedient i, si no es selecciona un tipus abans, no sabem quins estats s'han de mostrar al desplegable.
