### ISSUE TITLE
Error d'enviament a portafirmes no controlat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#610]
Si un dels destinataris d'una firma simple no és vàlid mostra un error no controlat. S'hauria de mostrar un missatge dins la finestra d'enviament i no sortir l'error 500

es.caib.portafib.ws.api.v1.WsValidationException: Destinatari ID(destinatariID): El camp Destinatari ID és obligatori.

![imatge](https://user-images.githubusercontent.com/58417501/97561523-9817d700-19e0-11eb-9216-9388da422c26.png)

**Comment by acuevas-dgtic** [comment]
Ej error sigue produciéndose

**Comment by josepg-limit** [comment]
Hem vist que l'error que passa ara és diferent a l'error de la incidència. L'error ara és: 
es.caib.ripea.plugin.SistemaExternException: No s'ha trobat cap usuari persona amb id = [...]

**Comment by acuevas-dgtic** [comment]
varias cosas:

1. Ahora tarda una barbaridad en mostrar el resultado del desplegable responsables. Se queda casi medio minuto en "Searching...."
2. Si borras los responsables por defecto del tipo de documento y pones otros, tras el mensaje de error  te vuelven a aparecer estos en lugar de los que has modificado
3. Al cerrar la pantalla de enviar se queda colgado
