### ISSUE TITLE
No es tanca la finestra de firma amb firma pasarel·la

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#611]
Una vegada signat el document amb firma passarel·la no es tanca la finestra.

**Comment by acuevas-dgtic** [comment]
Adreça que es mostra https://proves.caib.es/ripea/passarelaModalTancar

**Comment by josepg-limit** [comment]
Tot pareix indicar que hi ha hagut canvis en la pàgina de Portafib que mostra el final del procés i això fa que el comportament de RIPEA a l'hora de finalitzar el procés de firma no sigui el que toca.

**Comment by acuevas-dgtic** [comment]
Ara surt un erro 500 amb un Nullpointer
```
java.lang.NullPointerException
	es.caib.ripea.war.controller.DocumentController.firmaPassarelaFinal(DocumentController.java:515)
```

**Comment by acuevas-dgtic** [comment]
A més, la finestra de ripea desapareix i només es mostra el procés de signatura en portaifb

**Comment by acuevas-dgtic** [comment]
No apareix cap finestra modal, el procés de firma es posa en pantalla completa.

**Comment by josepg-limit** [comment]
Los cambios hechos en Portafib nos impiden mostrar todo el proceso de firma en una ventada modal.

RIPEA muestra las pantallas del proceso de firma (procedentes de Portafib) en un iframe y, al finalizar el proceso, Portafib fuerza a que una de las pantallas se muestre en la ventana principal del navegador. Esto hace que se pierda la ventana modal.

La única forma de evitar esto es que Portafib no fuerce que las páginas de la pasarela de firma se muestren en la ventana principal del navegador. Desde RIPEA no podemos controlarlo.
