### ISSUE TITLE
Revisar la funcionalitat de gestió d'expedients per usuaris administradors

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#626]
Aquesta funcionalitat ha de permetre accedir als expedients des de les pantalles del rol d'administrador corresponent. No com es fa ara que s'accedeix a la funcionalitat des de les pantalles dels usuaris tramitadors.

**Comment by acuevas-dgtic** [comment]
- [ ] L'administrador està veient tots els expedients dins del perfil d'usuari. Amb aquest perfil, només ha de veure els procediments dels que tingui accés. Sí ha de veure tots dins el perfil "Administrador d'entitat".
- [ ] L'administrador d'òrgan només ha de veure els expedients dels organismes del que tingui accés. Esta veient tots del govern.

**Comment by acuevas-dgtic** [comment]
L'administrador està veient tots els expedients dins del perfil d'usuari. Amb aquest perfil, només ha de veure els procediments dels que tingui accés. Sí ha de veure tots dins el perfil "Administrador d'entitat" o "Administrador d'òrgan" segons el cas
