### ISSUE TITLE
Problema gestió procediments comuns

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#628]
- [ ] Un usuari que no té assignat cap permís a cap DIR3 pot gestionar tots els expedients de procediments comuns creats/gestionats per qualsevol DIR3.
- [ ] Un usuari amb permisos a un DIR3 pot gestionar els expedients comuns creats/gestionats per altres DIR3. L’usuari només hauria de veure els expedients creats/gestionats pel seu DIR3.

**Comment by josepg-limit** [comment]
Es varen fer les següents comprovacions i no es va detectar cap error:
**Cas de prova 1:** Donat un usuari amb els rols d'administració d'entitat i administrador d'òrgan gestor sense cap permís a cap organ gestor:
* No pot accedir a la funcionalitat d'administrador d'òrgan (No li apareix l'opció a dalt).
* Al accedir com a rol de Administrador d'entitat pot gestionar tots els metaexpedients de l'entitat actual.
* Pot crear expedients dels tipus d'expedients als quals se li ha donat permís explícitament.

Tot pareix correcte.

**Cas de prova 2:** Al mateix usuari se li ha donat permís sobre un òrgan gestor
* Li apareix l'opció per accedir a la funcionalitat d'administrador d'òrgan. Li apareixen únicament els tipus d'expedients de l'òrgan gestor sobre els que té permís.
* Al accedir com a rol de Administrador d'entitat pot gestionar tots els metaexpedients de l'entitat actual.
* Pot crear expedients dels tipus d'expedients als quals se li ha donat permís explícitament.

Tot pareix correcte.
