### ISSUE TITLE
Revisar documents de notificacions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#633]
Si la notificació no s’ha pogut fer perquè el procediment no existeix a NOTIB, no s’ha fet cap notificació, però a l’apartat «informació obtinguda de l’arxiu», apareixen documents de notificacions. S’hauria de comprovar quins són aquest documents (no sé exactament que informa aquest apartat, però si són documents de l’arxiu, s’hauria de comprovar que es guarda exactament, jo no tinc manera).

**Comment by josepg-limit** [comment]
No s'ha pogut reproduir l'error
