### ISSUE TITLE
Error firma amb pasarel·la

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#636]
Dóna un error 404 a l'hora de realitzar una signatura en servidor

![imatge](https://user-images.githubusercontent.com/58417501/100731435-aa17db80-33cb-11eb-9ecb-374d82594a35.png)

**Comment by josepg-limit** [comment]
Todo parece indicar que el problema proviene de que, al no estar definida la propiedad de la URL base, RIPEA intenta calcular por sus propios medios la URL de retorno y utiliza el protocolo HTTP en lugar de HTTPS.
