### ISSUE TITLE
Problema accés dels administradors d'òrgan

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#642]
Els administradors d'òrgan no poden accedir a RIPEA. Dóna error 500. Pareix que s'està produint des de que s'ha implementat la issue #568. L'usuari te assignat el rol IPA_ORGAN_ADMIN.

**Comment by josepg-limit** [comment]
causa raíz

java.lang.IllegalArgumentException: Parameter value [null] was not matching type [es.caib.ripea.core.entity.AclSidEntity]
org.hibernate.ejb.AbstractQueryImpl.registerParameterBinding(AbstractQueryImpl.java:340)
org.hibernate.ejb.QueryImpl.setParameter(QueryImpl.java:364)
org.hibernate.ejb.QueryImpl.setParameter(QueryImpl.java:72)
org.springframework.data.jpa.repository.query.ParameterBinder.bind(ParameterBinder.java:131)
org.springframework.data.jpa.repository.query.StringQueryParameterBinder.bind(StringQueryParameterBinder.java:61)
org.springframework.data.jpa.repository.query.ParameterBinder.bind(ParameterBinder.java:110)
org.springframework.data.jpa.repository.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:153)
org.springframework.data.jpa.repository.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:144)
org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.doCreateQuery(AbstractStringBasedJpaQuery.java:68)
org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:164)
org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:81)
org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:59)
org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:97)
org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:88)
org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:404)
org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:364)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:155)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:119)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
com.sun.proxy.$Proxy505.findObjectsWithPermissions(Unknown Source)
es.caib.ripea.core.helper.PermisosHelper.getObjectsIdsWithPermission(PermisosHelper.java:172)
es.caib.ripea.core.helper.OrganGestorHelper.findOrganismesEntitatAmbPermis(OrganGestorHelper.java:30)
es.caib.ripea.core.service.OrganGestorServiceImpl.findOrganismesEntitatAmbPermis(OrganGestorServiceImpl.java:199)
sun.reflect.GeneratedMethodAccessor1169.invoke(Unknown Source)
[..]
