### ISSUE TITLE
Amagar el botó d'agafar expedient

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#648]
Amagar el botó d'agafar expedient quan l'usuari no te permisos sobre aquest o informar que l'usuari no te permisos

**Comment by santich-dgtic** [comment]
Com usuari tampoc t'hauria de deixar crear un expedient d'un tipus que no tens permisos.

**Comment by josepg-limit** [comment]
No se ha podido reproducir, ya esta resuelto
