### ISSUE TITLE
Modificar funcionament dels permisos d'administrador d'òrgan

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#651]
Revisar l'actual funcionalitat de permisos d'administrador d'òrgan per a que el seu funcionament sigui anàleg a l'actual de NOTIB.

**Comment by acuevas-dgtic** [comment]
Al igual que Notib, s'ha de poder donar permisos als usuaris a nivell d'òrgan per poder tramitar tots els expedients d'aquest òrgan sense necessitat d'anar donant permisos un per un. Aquesta opció ha d'estar disponible pels administradors d'entitat i d'òrgan, encara que només els administradors d'entitat han de poder donar permisos d'administració.

**Comment by acuevas-dgtic** [comment]
Faltaria afegir una opció de seleccionar tots (excepte administració) similar a Notib

![imatge](https://user-images.githubusercontent.com/58417501/113828156-5dcb1680-9784-11eb-91fa-d599a708c4e0.png)
