### ISSUE TITLE
Importar definició de tipus d'expedient des de ROLSAC

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#652]
Afegir un importador de tipus d'expedient des de ROLSAC a partir d'un codi SIA. Importar el  NOM, DESCRIPCIÓ, ÒRGAN GESTOR i si és o no comú. Aquesta opció ha d'estar disponible pels administradors d'entitat i d'òrgan. Els d’òrgan només han de poder importar expedients del seu organisme o dependents.

**Comment by josepg-limit** [comment]
Añadir campo comun

**Comment by acuevas-dgtic** [comment]
S'ha de moure el camp "Codi SIA" i el botó d'importar després del camp Codi intern
