### ISSUE TITLE
Error de conversió a PDF

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#667]
El sistema dóna un error de conversió a PDF quan es vol convertir un ODT o DOC

![imatge](https://user-images.githubusercontent.com/58417501/105006489-0a73e280-5a37-11eb-987b-f2dac428dced.png)

**Comment by josepg-limit** [comment]
Todavía no hemos podido reproducirlo pero pudimos reproducir y corregir el error de la issue: "#655 Error al generar índex de l'expedient" que creemos que fue causado por el mismo problema y al corregir el error #655 no va a pasar mas.
