### ISSUE TITLE
Problema firma amb pasarel·la

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#670]
A l'hora de firmar un document amb firma des del navegador dóna un error 404. Pareix que la URL mostra /ripea/ dues vegades
![imatge](https://user-images.githubusercontent.com/58417501/105459009-d04e4f00-5c89-11eb-9079-92310188212a.png)

![imatge](https://user-images.githubusercontent.com/58417501/105458967-bf9dd900-5c89-11eb-85ac-62acae90fec0.png)

**Comment by josepg-limit** [comment]
Ahora funciona en todos los entornos, quizás fué un error puntual
