### ISSUE TITLE
Revisar camp CSV a la pipella firmes de la informació d el'arxiu d'un document

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#678]
Quan es consulta la informació d’un document signat, a la informació de firma surt el CSV, que a la CAIB només s’empra com a localitzador. S’ha estat pensant si el CSV hauria de sortir com a firma o no, però com que altres organismes poden emprar el CSV per firmar i a RIPEA es pot guardar qualsevol document signat, es creu que en alguns casos s’hauria de mostrar com està actualment. Si només s’empra com a localitzador, és a dir, si la metadada eni:tipoFirma no conté el valor TF01 (signatura amb CSV), llavors no hauria de sortir com a firma CSV ja que resultaria incoherent a nivell de metadades. La metadada eni:tipoFirma hauria de ser de cardinalitat múltiple i com a firmes a mostrar en la pestanya de firmes mostraria les dades de firma de cada una d’elles.

![imatge](https://user-images.githubusercontent.com/58417501/106589117-ef7f9300-654b-11eb-950a-59bd728dfc9e.png)

**Comment by josepg-limit** [comment]
Aquesta issue s'ha de solucionar al plugin d'arxiu. Issue de l'arxiu relacionada: #40
