### ISSUE TITLE
Revisar metadada eni:app_tramite_doc 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#682]
La metadada eni:app_tramite_doc és el nom de l’aplicació que crea el document al gestor documental. Aquest conjunt de valors possibles hauria d’estar definit a l’arxiu i no s’hauria de donar marge a posar qualsevol valor.

![imatge](https://user-images.githubusercontent.com/58417501/106591117-2a82c600-654e-11eb-962f-1ba90f712249.png)

**Comment by josepg-limit** [comment]
Depen de pluginsib-arxiu #38

**Comment by josepg-limit** [comment]
No s'ha fet res en aquesta issue perquè el valor d'aquesta metadada la controla el plugin d'arxiu.
