### ISSUE TITLE
Error 500 al aceptar una anotación y crear expediente

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#764]
Al aceptar una anotación en un backoffice de dev salta el error que adjunto.

![image](https://user-images.githubusercontent.com/17267008/116664452-c6c73800-a998-11eb-841d-075dff11b8e1.png)

**Comment by acuevas-dgtic** [comment]
Varis errors:

- [ ] Un usuari té accés a totes les anotacions pendents encara que no tengui accés al tipus d'expedient.
- [ ] Al acceptar l'anotació i dir-li que cregui l'expedient pareix que no fa res ja que continua sortint en el llistat d'anotacions pendents i no es crea l'expedient.
 ![imatge](https://user-images.githubusercontent.com/58417501/116986804-89331980-acce-11eb-966d-966e9707951d.png)

- [ ] AL filtrar per tipus d'expedient com a administrador surt un error
![imatge](https://user-images.githubusercontent.com/58417501/116987380-49b8fd00-accf-11eb-9717-252f45f096a9.png)
