### ISSUE TITLE
Filtrar anotacions pendents per tipus d'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#767]
Ara mateix tots els usuaris poden veure totes les anotacions pendents. Això s'hauria de restringir i fer que els usuaris només puguin veure les anotacions amb tipus d'expedients sobre els quals es tenen permisos. Un usuari podrà veure les anotacions relacionades amb un tipus d'expedient sobre el qual l'usuari te permisos de creació o modificació.

A l'hora d'acceptar l'anotació, les accions de crear o incorporar estaran disponibles depenent dels permisos que tengui l'usuari sobre el tipus d'expedient.

Des de distribució es faran les modificacions necessàries per a assegurar que a RIPEA sempre arribaran les anotacions amb el codi de procediment emplenat.

També s'ha de fer una pantalla per a que els administradors d'entitat puguin veure les anotacions de registre pendents. En aquesta pantalla els usuaris administradors podran veure totes les anotacions de registre existents, sense restriccions de cap tipus, i podran fer les mateixes accions que els usuaris no administradors.

**Comment by acuevas-dgtic** [comment]
El camp destinació dels filtres hauria de ser un desplegable amb la llista d'òrgans amb accés

**Comment by acuevas-dgtic** [comment]
També s'ha d'afegir un filtre de tipus d'expedient

**Comment by acuevas-dgtic** [comment]
No s'actualitza el número d'anotacions pendents

![imatge](https://user-images.githubusercontent.com/58417501/117929232-da5d9180-b2fc-11eb-9722-89ea61722db1.png)

**Comment by acuevas-dgtic** [comment]
El filtre destinació ha de mostrar només les unitats a las que tingui accés l'usuari

![imatge](https://user-images.githubusercontent.com/58417501/118108015-c50d6380-b3df-11eb-98cd-bb6904b4fa6d.png)
