### ISSUE TITLE
Permetre consultar i modificar l'òrgan dels expedients

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#844]
S'ha de permetre consultar l'òrgan a tots els usuaris que tenguin accés a un expedient. Aquesta informació hauria d'aparèixer a la columna esquerra de la pantalla de consulta de l'expedient.

A més, els usuaris administradors d'entitat també haurien de poder modificar l'òrgan assignat a un expedient.

Aquesta modificació hauria d'estar disponible també per a la versió 0.9.85, per a poder desplegar-ho a producció.

**Comment by acuevas-dgtic** [comment]
Aquesta opció només ha d'estar disponible per a un tipus d'expedient comú

**Comment by acuevas-dgtic** [comment]
Aquesta opció només ha d'estar disponible per a un tipus d'expedient comú

**Comment by acuevas-dgtic** [comment]
L'administrador d'entitat ha de poder indicar qualsevol òrgan a un expedient d'un procediment comú. Actualment només pot seleccionar els òrgans al que té accés com a perfil usuari.
