### ISSUE TITLE
permisos multiples a nivel de tipus d'expedient

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/ripea#862]
se estan permitiendo permisos multiples en la aplicación y posteriormente no se aplican todos
![Captura Doble rol](https://user-images.githubusercontent.com/86109941/133614488-60af0c3b-43d4-4c34-9923-00922279678c.PNG)
en la captura podemos ver que primero se asigna un permiso sin organo gestor, al crear un expediente salen multitud de organos para asignar, si creamos el segundo rol con el OG de Modernización solo nos permite asignarlo a modernización.
Al crear un tercer permiso con otra DG nos permite asignarlo a Modernización y a la otra DG y sus suborganos por lo tanto parece mas una incongruencia con el permiso sin OG.

**Comment by acuevas-dgtic** [comment]
Aquesta situació ve donada en l'entorn de desenvolupament perquè es va crear el procediment abans d'implementar-se els procediments comuns. He creat la issue #864 per evitar afegir permisos sense òrgan en un procediment comú
