### ISSUE TITLE
Acceptació de annotacions pendents (crear expedient)

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/ripea#871]
Cuando intentamos crear un expediente nuevo al acceptar una annotación pendiente nos aparece el siguiente mensaje de error
![imatge](https://user-images.githubusercontent.com/86109941/133751812-62120507-fc5a-49f1-8f2a-4edd12bd8e7c.png)

**Comment by josepg-limit** [comment]
Tancam perquè aquesta issue és duplicada de la #870.
