### ISSUE TITLE
Afegir acció manual per custodiar expedient dins l'arxiu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#873]
Si un expedient no s'ha pogut custodiar dins l'arxiu, no hi ha manera de forçar-ho. Afegir una acció manual a la llista d'accions de l'expedient per guardar a l'arxiu, similar a la que hi ha pels documents

![image](https://user-images.githubusercontent.com/58417501/133969674-d36664fa-9a77-424a-96ee-a69b3126f5e6.png)
![image](https://user-images.githubusercontent.com/58417501/133969775-b5e096b3-b168-4ea8-ae22-50d01ba67290.png)

**Comment by josepg-limit** [comment]
Ja resolt en issue #793: Permetre crear expedients i documents encara que l'arxiu doni error
