### ISSUE TITLE
Modificar detalls de la notificació i afegir justificant d'enviament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#885]
- [x] S'ha de substituir el justificant de registre pel justificant d'enviament que genera el propi notib.
- [x] El contingut de la pipella "Registre" dels detalls de l'enviament s'ha de moure a la pipella principal.
- [x] Els detalls de l'enviament han de ser els més semblants possibles als de notib

RIPEA:
![image](https://user-images.githubusercontent.com/58417501/139397882-8563d77b-9052-47ba-ad29-9a806ffc3646.png)
![image](https://user-images.githubusercontent.com/58417501/139397387-f7f284d0-7e67-4efa-ad97-d10814cd5d4c.png)

NOTIB:
![image](https://user-images.githubusercontent.com/58417501/139397768-5cc6c542-cf0b-41e0-afc1-0d4589701a76.png)

Justificant d'enviament
![image](https://user-images.githubusercontent.com/58417501/139397468-4a0553ff-1d8b-44eb-bc78-880ad5ebf487.png)

**Comment by acuevas-dgtic** [comment]
Ja surt el justificant d'enviament i les dades de registre però el format dels detalls és diferents als detall en Notib. S'ha de revisar

**Comment by acuevas-dgtic** [comment]
La columna "Destinataris" s'ha de dir "Representants"

![image](https://user-images.githubusercontent.com/58417501/154220736-58b4307d-475a-4808-8fca-3f8109f69449.png)

La pipella "Notificacions" s'ha de dir "Remeses", igual que en Notib

![image](https://user-images.githubusercontent.com/58417501/154221658-53c08f82-e9dc-4b8b-90f8-32442e7d2cef.png)

**Comment by acuevas-dgtic** [comment]
Revisar els camps "Enviada el" i "Estat data". Crec que la primera és la data de creació i la segona la data d'enviament. Deixar-lo com a Notib

![image](https://user-images.githubusercontent.com/58417501/154224035-a66615c3-1d69-402b-925f-2d11de68fc2b.png)

**Comment by josepg-limit** [comment]
Actualment no es disposa de les mateixes dates que en Notib. En la propera versió, quan es disposi del client modificat de Notib, es realitzaran els canvis necessaris per a mostrar la mateixa informació de la que disposa en Notib.
Així, en aquesta versió no s'ha pogut posar la data d'enviament o la de processat, ja que no es tenen. Al tenir el client de Notib actualitzat es podrà acabar de refinar la informació de les notificacions.

**Comment by acuevas-dgtic** [comment]
ok, ho farem més endavant, però sí es pot modificar els literals "Destinataris" i "Notificacions" que he proposat
