### ISSUE TITLE
Eliminar tasques de forma automàtica al eliminar un procediment

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#903]
Dóna error SQL si no se eliminen les tasques prèviament

![image](https://user-images.githubusercontent.com/58417501/142194638-9a20e8b1-9aa1-4f68-9b3d-4fe9cd206e00.png)

**Comment by josepg-limit** [comment]
Commit: [5d55a2a](https://github.com/GovernIB/ripea/commit/5d55a2ad9a29f7a530b06b647a4287eb39325e99)
