### ISSUE TITLE
Solucionar problemes amb la paginació

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/ripea#905]
En moure's per la paginació dels procediments en canviar algunes pantalles són iguals que les anteriors, per tant es perd visibilitat d'alguns procediments.

**Comment by josepg-limit** [comment]
S'ha comprovat que l'error es produïa quan s'ordenava per alguna columna amb valors repetits, com la sèria documental.
Per evitar el problema s'ha afegit sempre una subordenació per nom.
