### ISSUE TITLE
Revisar taules de monitorització de superusuari

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/ripea#909]
Pareix que quan estas com a superusuari mirant les monitoritzacions, un text indica que s'estan mostrant les entrades de 1-10, la taula mostra 20 resultats (amb el seleccionable posat amb 10), posa que te 2 pàgines i les dues mostren la mateixa informació.

**Comment by josepg-limit** [comment]
Detectat un error durant la validació en la conversió dels paràmetres de la pàgina.
