### ISSUE TITLE
Afegir propietat per a definir el procediment pinbal a utilitzar per defecte

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#929]
Afegir una propietat a RIPEA que en cas d'estar informada s'utilitzi per a totes les crides (independentment del procedimento) i si està buida que utilitzi el códi SIA de cada procediment.

**Comment by josepg-limit** [comment]
Afegida la propietat _es.caib.ripea.pinbal.codi.sia.peticions_.
Aquesta propietat es pot configurar com a superusuari, a l'apartat Plugins > Plugin de Pinbal, de la configuració de propietats.

**Comment by acuevas-dgtic** [comment]
La propiedad no es correcta. Habíamos pedido código de procedimiento, no código SIA

**Comment by acuevas-dgtic** [comment]
El parámetro admite tanto el código SIA como el código de procedimiento. Se ha pedido modificar el literal para que quede más claro

**Comment by acuevas-dgtic** [comment]
Se ejecutó sql para actualizar la descripción de la propiedad
