### ISSUE TITLE
Indicar d'alguna manera que el filtre de procediment a l'acció massiva d'enviar documents al portafirmes es obligatoria

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/ripea#943]
Hauria de quedar clar a l'acció massiva d'enviar documents al portafirmes que si es desitja filtrar es obligatori indicar el procediment.

El procediment s'hauria de poder filtrar per codi.

**Comment by acuevas-dgtic** [comment]
Hecho en la #1290
