### ISSUE TITLE
Revisar funcionalitat de incorporar una anotació a un expedient existent

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#948]
CREAR EXP

A partir del tràmit test-registre, m'ha anat tot bé a la primera a l'hora de Crear un Expedient!
 :-)

![imatge](https://user-images.githubusercontent.com/17267008/153224747-5de34be7-582e-4ba2-a8b5-07326e0c98a4.png)

INCORPORAR A EXP

2.- A RIPEA, quan incorporam el mateix tràmit d'inici (amb una nova anotació de registre):

![imatge](https://user-images.githubusercontent.com/17267008/153224788-7a67db12-a665-4361-8e34-4b112dae1a95.png)

Pareix que hi ha tots els annexos però hi manca el formulari... També ens xoca que no trobam informació de l'Anotació de Registre GOIBE593/2022, que és la que ha introduit l'annex de les 12.49

![imatge](https://user-images.githubusercontent.com/17267008/153224835-2ffa9b34-67ec-4eee-a0b5-570cc39c0cc4.png)

En una tercera prova no annexa els 3 documents de l'anotació GOIBE595/2022i a més, tot i desactivar l'interessat, ens demana això:

![imatge](https://user-images.githubusercontent.com/17267008/153224895-97533ac7-0aa0-4600-aba6-683d0c4f635c.png)

![image](https://user-images.githubusercontent.com/58417501/153227659-746e2284-78df-4517-9473-fa1ce8b4cded.png)

**Comment by acuevas-dgtic** [comment]
Hi ha un problema amb noms repetits. Per exemple, en l'expedient amb número S2_RIPEA_II/8/2022 l'anotació GOIBE547/2022 ha donat error al fitxer XML de formulari. Pareix que s'està intentant guardar un document amb el mateix nom que un document ja existent

**Comment by acuevas-dgtic** [comment]
Para evitar errores de archivo por nombres de documentos duplicados se creará una subcarpeta por cada anotación.

**Comment by acuevas-dgtic** [comment]
Se entiende que estas subcarpetas son a nivel de archivo, en RIPEA no deben aparecer carpetas
