### ISSUE TITLE
Detalls de l'anotació de registre - Annexos

### ISSUE THREAD

**Issue by salvadorAnt** [GovernIB/ripea#955]
en els detallas dels firmants no surten els noms dels signants a davora la data de signatura
![Captura de pantalla de 2022-02-22 08-48-09](https://user-images.githubusercontent.com/46705890/155086435-92e797e4-679b-4b6c-a579-5c107dbcba24.png)

**Comment by acuevas-dgtic** [comment]
En l'entorn de producció si es mostra els noms.
