### ISSUE TITLE
Permetre firmar en servidor documents en l'acció massiva de tancar expedients

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#962]
Antes no se podían cerrar expedientes sin documentos firmados, por eso se mejoró el cierre de expedientes de manera que los borradores se pueden firmar en servidor al cerrar el expediente:

![image](https://user-images.githubusercontent.com/58417501/155937343-00b559de-93d7-4a5f-bb1c-bda7b3ac7dc4.png)

Esta mejora no se implementó en la acción masiva, donde todavía se eliminan todos los borradores, sin dar opción a firmar en servidor.

![image](https://user-images.githubusercontent.com/58417501/155937313-f0d233c0-0d03-497d-94c9-839379ec7bca.png)

**Comment by jvazquez-dgtic** [comment]
al intentar cerrar da el siguiente error:
![image](https://user-images.githubusercontent.com/86109941/162187187-d58dc2bb-89ad-40d9-9343-55a2aba1217c.png)
