### ISSUE TITLE
Error al enviar un document docx a portafirmes

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#964]
S'ha detectat que al intentar realitzar la conversió d'un document docx a pdf l'aplicació dóna error:

![imatge](https://user-images.githubusercontent.com/17267008/156342416-23203905-ad5f-4f9a-b3a0-28ec062a073a.png)

![imatge](https://user-images.githubusercontent.com/17267008/156342432-8e8fb48e-2cad-4b5a-bc35-12e55fca3fd3.png)

**Comment by jvazquez-dgtic** [comment]
segueix sense funcionar
![imatge](https://user-images.githubusercontent.com/86109941/157199283-bb5bff61-da5b-4966-b826-ab0e01a0976c.png)

si pitjam previsualitzar
![imatge](https://user-images.githubusercontent.com/86109941/157199116-a9173bea-370f-493e-a99b-1967e518568e.png)
