### ISSUE TITLE
Poder veure les dades dels interessats quan un expedient està tancat

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#988]
Permetre desplegar el detall dels interessats quan un expedient està tancat. Amb la implementació actual no és possible consultar aquesta informació.

**Comment by acuevas-dgtic** [comment]
Evitar que mostri null

![image](https://user-images.githubusercontent.com/58417501/162142976-a9f5748a-7ae1-40dc-8951-90a8f64fd5e5.png)
