### ISSUE TITLE
Deshabilitar l'acció informació d'arxiu d'un document si està pendent de custodiar

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#990]
Aquesta situació no té sentit

![image](https://user-images.githubusercontent.com/58417501/159508595-ac709ade-d344-4c54-9dba-d9d055e29c04.png)

**Comment by acuevas-dgtic** [comment]
Hemos detectado que se sigue dando en la 0.9.96

![image](https://user-images.githubusercontent.com/58417501/212008250-3549ae5c-e250-4be9-bc9f-fd4c1232725f.png)

**Comment by josepg-limit** [comment]
Ya funciona de esta manera
